# To deplpy anagram to AWS lambda

- name: Deploy from Gav MacBook
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Ansible zip multiple files example
    archive:
      path:
        - /Users/webdev/git/loyalty_anagram/lambda_function.py
        - /Users/webdev/git/loyalty_anagram/my_dict.txt
      dest: /Users/webdev/git/loyalty_anagram/function.zip
      format: zip

  - name: Update lambda function in AWS
    lambda:
      name: 'AnagramTest'
      state: present
      zip_file: '/Users/webdev/git/loyalty_anagram/function.zip'
      runtime: 'python3.7'
      role: 'arn:aws:iam::490863627463:role/service-role/AnagramTest-role-iuqupp3o'
      handler: 'lambda_function.lambda_handler'
      memory_size: '512'
      timeout: 120
